### ISSUE TITLE
Home Assistant 2023.8.0 - Error adding entities for domain switch

### ISSUE THREAD

**Issue by chrisandsally** [KaSroka/Toshiba-AC-control#41]
Sorry folks, Error when updated to 2023.8.0

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:619 
Integration: Switch (documentation, issues) 
First occurred: 21:47:58 (2 occurrences) 
Last logged: 21:47:58

Error adding entities for domain switch with platform toshiba_ac
Error while setting up toshiba_ac platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'account'

**Comment by chrisandsally** [comment]
Wrong thread, I think
